apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cirra.fullname" . }}-files
  labels: {{- include "cirra.labels" . | nindent 4 }}
spec:
  accessModes: [{{ .Values.storage.accessMode }}]
  {{- with .Values.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources: { requests: { storage: {{ .Values.storage.size }} } }
