"""Help center content for business users: role guides, functional areas with how-tos, process maps, glossary,
shortcuts and release notes. Plain data, so Aiden can search it and the UI can render it (services/help.py).

Links are app routes; ``roles`` lists who an item is written for (empty = everyone)."""

ROLES = {
    "super_admin": {
        "title": "Super Admin", "mission": "Run the workspace: people, access, security, data quality, automation and integrations.",
        "day": [("Check sign-in security and pending users", "/admin?tab=users"), ("Review the audit trail for unusual changes", "/admin?tab=audit"),
                ("Keep duplicates down", "/admin?tab=dedup"), ("Watch AI spend and approvals", "/admin?tab=ai"),
                ("Check background jobs and integrations", "/admin?tab=jobs")],
        "areas": ["admin", "workflows", "ai-governance", "platform", "data", "finance"],
        "checklist": ["Turn on two-factor authentication for every role that handles customer data",
                      "Review the roles & permissions matrix against your org chart", "Set AI budgets and the agents' approval mode",
                      "Choose the tax engine and load exchange rates", "Connect SSO if your company uses Entra ID, Okta or Google"],
        "tips": ["Every admin change is in the audit trail, including who changed a permission and when.",
                 "Validation and sharing rules apply to people's saves; workflows and jobs act as the system."],
    },
    "sales_manager": {
        "title": "Sales Manager", "mission": "Coach the team, own the forecast and keep deals moving through the gates.",
        "day": [("Read the morning briefing", "/"), ("Review deals at risk in the pipeline", "/pipeline"),
                ("Approve discounts waiting on you", "/approvals"), ("Check team quota attainment", "/performance"),
                ("Submit or adjust the forecast call", "/performance")],
        "areas": ["pipeline", "forecast", "cpq", "reports", "accounts", "ai"],
        "checklist": ["Set quarterly quotas for each rep", "Agree the stage gates your team must evidence",
                      "Subscribe to the pipeline report every Monday", "Decide which AI suggestions need your approval"],
        "tips": ["Weighted pipeline discounts risky deals: amount × probability × (1 − risk / 200).",
                 "You can override a stage gate; it is recorded in the deal's stage-gate audit trail."],
    },
    "account_executive": {
        "title": "Account Executive", "mission": "Win and grow your accounts: qualify, run the sales process, quote and close.",
        "day": [("Start with Aiden's briefing", "/"), ("Log calls and meetings with Quick-Log (⌘K)", "/"),
                ("Move your deals forward on the board", "/pipeline"), ("Work today's tasks", "/tasks"), ("Build and send quotes", "/quotes")],
        "areas": ["pipeline", "accounts", "activities", "cpq", "documents", "ai"],
        "checklist": ["Connect your mailbox and calendar in Settings", "Map the buying committee on each open deal",
                      "Add products to deals so the amount follows them", "Check your quota and commission statement"],
        "tips": ["Paste raw meeting notes into Quick-Log: Aiden extracts contacts, the deal update and follow-up tasks.",
                 "A deal team member with read access can see but not change your deal; give 'edit' to co-sellers."],
    },
    "sdr": {
        "title": "Sales Development Rep", "mission": "Turn inbound and outbound interest into qualified meetings for the account executives.",
        "day": [("Work new leads by score", "/leads"), ("Qualify with BANT or MEDDPICC", "/leads"), ("Log calls quickly", "/"),
                ("Hand over qualified leads (convert)", "/leads")],
        "areas": ["leads", "activities", "campaigns", "ai"],
        "checklist": ["Learn the scoring model: fit (who they are) plus engagement (what they did)",
                      "Use the qualification checklist before converting", "Keep lead statuses current so routing works"],
        "tips": ["A lead becomes an MQL at the score threshold; converting creates the account, contact and opportunity in one step."],
    },
    "auditor": {
        "title": "Auditor", "mission": "Review who did what, when, with read-only access to records and the audit trail.",
        "day": [("Search the audit trail", "/admin?tab=audit"), ("Check privacy and consent records", "/admin?tab=privacy"),
                ("Run and export reports", "/reports")],
        "areas": ["admin", "reports", "privacy"],
        "checklist": ["Learn the audit trail filters (user, record, field)", "Know where erasure and consent evidence lives"],
        "tips": ["The audit trail and the privacy ledgers are append-only: the database itself refuses edits and deletes."],
    },
    "partner": {
        "title": "Partner", "mission": "Register deals, co-sell and track your commissions through the partner portal.",
        "day": [("Register a new opportunity", "/portal"), ("Check registration status", "/portal"), ("Download collateral", "/portal")],
        "areas": ["partners"],
        "checklist": ["Register deals early: approved registrations protect your commission"],
        "tips": ["You see only your own registrations and the deals shared with your partner organisation."],
    },
    "support_agent": {
        "title": "Support Agent", "mission": "Resolve customer cases within their SLA and keep the knowledge base useful.",
        "day": [("Set yourself available", "/cases/routing"), ("Work your queue", "/cases"), ("Answer the support inbox", "/cases/inbox"),
                ("Suggest or write articles", "/knowledge")],
        "areas": ["service", "accounts", "activities"],
        "checklist": ["Know the SLA targets per priority", "Link cases to the right contact and account", "Use suggested articles in replies"],
        "tips": ["Replying from a case emails the customer and threads their answer back onto the case.",
                 "Presence routing only assigns cases to agents marked available, up to their capacity."],
    },
    "marketing": {
        "title": "Marketing", "mission": "Generate and nurture demand, and prove which campaigns create pipeline.",
        "day": [("Plan and run campaigns", "/campaigns"), ("Build nurture journeys", "/campaigns"), ("Check attribution and ROI", "/campaigns"),
                ("Watch lead quality", "/leads")],
        "areas": ["campaigns", "leads", "reports"],
        "checklist": ["Always check the consent preview before sending", "Tag campaigns with a code so web forms and UTMs attribute correctly",
                      "Use journeys for multi-step nurtures instead of one-off blasts"],
        "tips": ["Opt-outs and consent are enforced at send time: blocked people are listed in the preview with the reason."],
    },
}

AREAS = [
    {"key": "home", "title": "Home & daily briefing", "icon": "home", "pages": ["/"], "roles": [],
     "summary": "Your start page: Aiden's briefing, today's priorities, deals needing attention and upcoming closes.",
     "capabilities": ["Morning briefing written from your pipeline and tasks", "Priorities ranked by urgency and deal value",
                      "Risk alerts: stagnant deals, slipped close dates, sentiment drops, missing buying roles"],
     "howto": [{"q": "What should I work on first today?", "steps": ["Open Home", "Read the briefing headline", "Start with the top priority; each links to its record"]}]},
    {"key": "ai", "title": "Aiden, Quick-Log & AI assistance", "icon": "sparkles", "pages": ["/ask"], "roles": [],
     "summary": "Aiden turns raw notes and voice into structured CRM updates, answers questions over your data and drafts emails.",
     "capabilities": ["Quick-Log (⌘K): paste or dictate notes → contacts, deal update, activity and tasks, previewed before saving",
                      "Ask Aiden (⌘J): questions over your pipeline, notes and emails, with sources", "Email drafts and account briefs",
                      "Stage assistant and pipeline monitor agents (under your admin's approval policy)",
                      "Personal data is masked before any AI model sees it"],
     "howto": [{"q": "How do I log a meeting quickly?", "steps": ["Press ⌘K (Ctrl+K)", "Paste your notes or record a voice memo",
                                                                   "Check the preview: account, people, deal update, tasks", "Choose Save"]},
               {"q": "How do I ask Aiden a question?", "steps": ["Press ⌘J or choose Aiden in the header", "Type the question in plain language",
                                                                  "Open the cited sources to check the answer"]},
               {"q": "Why was an AI change waiting for approval?", "steps": ["Open Approvals → AI suggestions",
                                                                              "Read the reason Aiden gives", "Approve to apply it, or reject"]}]},
    {"key": "leads", "title": "Leads & qualification", "icon": "magnet", "pages": ["/leads"], "roles": ["sdr", "marketing", "sales_manager", "account_executive"],
     "summary": "Capture, score, route and qualify leads, then convert them into accounts, contacts and opportunities.",
     "capabilities": ["Web forms, imports, campaigns and API capture with duplicate checks", "Fit + engagement scoring with MQL threshold",
                      "Assignment rules and round-robin routing", "BANT and MEDDPICC qualification checklists", "One-step conversion"],
     "howto": [{"q": "How do I convert a lead?", "steps": ["Open the lead", "Complete the qualification criteria",
                                                           "Choose Convert", "Pick or create the account and name the opportunity"]},
               {"q": "Why does this lead have that score?", "steps": ["Open the lead", "Read the score breakdown: fit factors and engagement events"]}]},
    {"key": "pipeline", "title": "Pipeline, deals & stage gates", "icon": "columns", "pages": ["/pipeline", "/deals"], "roles": ["account_executive", "sales_manager"],
     "summary": "Run opportunities through your sales process on a board, with evidence-based stage gates, risk scoring and next best actions.",
     "capabilities": ["Several pipelines with their own stages and probabilities", "Stage gates that ask for evidence (roles mapped, pain found, quote approved…)",
                      "Deal risk and next best actions", "Opportunity products, deal teams and revenue / overlay splits",
                      "Win / loss taxonomy and debriefs"],
     "howto": [{"q": "How do I move a deal to the next stage?", "steps": ["Open Pipeline", "Drag the card, or open the deal and choose the stage",
                                                                          "If a gate lists missing evidence, add it (or a manager overrides)"]},
               {"q": "How do I add products to a deal?", "steps": ["Open the deal", "In Products choose Add products",
                                                                    "Pick products and quantities (blank price uses the price book)",
                                                                    "Tick 'Deal amount = total of products' to keep the amount in sync", "Save"]},
               {"q": "How do I share a deal with a colleague or split credit?", "steps": ["Open the deal", "In Deal team choose +, pick the person, role and access",
                                                                                          "Under Splits choose Edit and add revenue splits totalling 100%"]}]},
    {"key": "accounts", "title": "Accounts, contacts & the 360 view", "icon": "building", "pages": ["/accounts", "/contacts"], "roles": [],
     "summary": "Everything about a customer on one page: hierarchy, people and buying roles, health, activity, contracts, cases and finance.",
     "capabilities": ["Account 360 with health, churn risk and relationship strength", "Parent / subsidiary hierarchies with roll-ups in US dollars",
                      "Buying committee mapping", "Duplicate detection and merge", "Privacy: consent, opt-outs, cryptographic erasure"],
     "howto": [{"q": "How do I see a customer's whole picture?", "steps": ["Open the account", "Use the tabs: overview, people, deals, commercial, service"]},
               {"q": "How do I merge duplicates?", "steps": ["Admin → Duplicates", "Review the suggested pair and reasons", "Choose Merge; every related record moves to the survivor"]}]},
    {"key": "activities", "title": "Activities, tasks, email & calendar", "icon": "check", "pages": ["/tasks"], "roles": [],
     "summary": "The timeline of every call, meeting, email and note, your tasks, and two-way sync with your mailbox and calendar.",
     "capabilities": ["Timeline on every account and deal", "Tasks with due dates, dependencies and escalation",
                      "Mailbox sync (inbox and sent mail) and sending from Cirra", "Two-way Google Calendar / Microsoft 365 sync", "iCal feed"],
     "howto": [{"q": "How do I connect my calendar?", "steps": ["Open Settings", "In Calendar sync choose Connect Google Calendar or Microsoft 365",
                                                                "Sign in and allow access; meetings with CRM contacts sync both ways"]},
               {"q": "How do I connect my mailbox?", "steps": ["Open Settings", "In Email sync choose Connect mailbox", "Enter your IMAP/SMTP details"]}]},
    {"key": "cpq", "title": "Products, quotes & approvals", "icon": "file", "pages": ["/products", "/quotes", "/approvals"], "roles": ["account_executive", "sales_manager"],
     "summary": "Configure, price and quote with price books, tiers, bundles and promotions; discounts route through the approval chain.",
     "capabilities": ["Products, bundles and product rules", "Customer and regional price books with volume tiers", "Promotions",
                      "Multi-level approval chain", "Tax estimate on every quote (built-in, India GST or Avalara)"],
     "howto": [{"q": "How do I create a quote?", "steps": ["Open the deal", "In Quotes choose New quote (or Create quote from the deal's products)",
                                                           "Add lines and discounts", "Save, then Submit for approval if a policy requires it"]},
               {"q": "Why does my quote need approval?", "steps": ["Open the quote", "See Approval routing: each level lists the reason (discount, terms, deal size, credit)"]}]},
    {"key": "documents", "title": "Documents & e-signature", "icon": "pen", "pages": ["/documents"], "roles": ["account_executive", "sales_manager"],
     "summary": "Generate NDAs, MSAs, SOWs and order forms from CRM data, negotiate redlines and collect signatures.",
     "capabilities": ["Templates filled from account, deal and quote data", "Versions, redline comments and diffs",
                      "Built-in e-signature: customer signs by link (expires, can be re-sent), the company countersigns inside Cirra",
                      "DocuSign / Adobe Sign when configured"],
     "howto": [{"q": "How do I send a document for signature?", "steps": ["Generate it from the deal or quote", "Pick the customer signer",
                                                                          "Choose Send for e-signature and share the link", "Countersign on the document page when the customer has signed"]}]},
    {"key": "orders", "title": "Orders & ERP", "icon": "package", "pages": ["/orders"], "roles": ["account_executive", "sales_manager"],
     "summary": "Closed-won deals become orders sent to the ERP, with billing schedules and acknowledgements.",
     "capabilities": ["Order readiness checks before Closed-Won", "Automatic order from the primary quote", "ERP hand-off and status"],
     "howto": [{"q": "Why can't I close this deal as won?", "steps": ["Open the deal", "Read Order readiness: every unticked item must be fixed first"]}]},
    {"key": "forecast", "title": "Quotas, forecasting & commission", "icon": "target", "pages": ["/performance"], "roles": ["sales_manager", "account_executive"],
     "summary": "Quotas, attainment with split credit, commission statements and the forecast call.",
     "capabilities": ["Quarterly quotas", "Forecast categories and submissions with manager adjustments",
                      "Commission plans with accelerators", "Territories with realignment"],
     "howto": [{"q": "How do I submit my forecast?", "steps": ["Open Quotas & commission", "Check the categories of your deals", "Submit commit and best case"]}]},
    {"key": "reports", "title": "Reports & dashboards", "icon": "chart", "pages": ["/reports"], "roles": [],
     "summary": "Build reports over any record type (including custom objects), chart them, pin them to dashboards and subscribe.",
     "capabilities": ["Report builder with filters, grouping and date buckets", "Dashboards", "Scheduled email subscriptions", "Export"],
     "howto": [{"q": "How do I build a report?", "steps": ["Open Reports → New report", "Choose the record type", "Add filters and groupings", "Save and optionally pin to a dashboard"]}]},
    {"key": "campaigns", "title": "Campaigns & journeys", "icon": "megaphone", "pages": ["/campaigns"], "roles": ["marketing", "sales_manager"],
     "summary": "Plan campaigns, build member lists, send consent-checked email, run nurture journeys and measure attribution.",
     "capabilities": ["Members from report filters", "Email with open / click tracking (sent in the background)",
                      "Journeys with waits and engagement branches", "Sourced and influenced pipeline, ROI"],
     "howto": [{"q": "How do I send a campaign email?", "steps": ["Open the campaign → Email", "Write subject and body and Save",
                                                                  "Check the recipients and blocked reasons", "Choose Send; the page updates when the background send finishes"]}]},
    {"key": "service", "title": "Service: cases, routing & knowledge", "icon": "lifebuoy", "pages": ["/cases", "/knowledge"], "roles": ["support_agent", "sales_manager"],
     "summary": "Customer cases with SLAs, email-to-case, presence-based routing and a knowledge base.",
     "capabilities": ["Email-to-case with threading", "Queues and presence routing", "SLA timers and breach alerts", "Knowledge articles and suggestions", "CSAT surveys"],
     "howto": [{"q": "How do I take new cases?", "steps": ["Open Service → Routing", "Set yourself Available and your capacity", "New cases arrive in your queue"]}]},
    {"key": "success", "title": "Customer success & renewals", "icon": "heart", "pages": ["/success"], "roles": ["account_executive", "sales_manager"],
     "summary": "Onboarding projects, adoption signals, contracts and the renewal engine.",
     "capabilities": ["Onboarding workspaces with milestones", "Product usage and health", "Renewal opportunities created ahead of contract end"],
     "howto": [{"q": "When are renewals created?", "steps": ["The renewal job opens a renewal deal ahead of each active contract's end date"]}]},
    {"key": "finance", "title": "Finance, tax & currency", "icon": "landmark", "pages": ["/finance"], "roles": ["super_admin", "sales_manager"],
     "summary": "Receivables and credit status from the ERP, exchange rates with history, and tax engines.",
     "capabilities": ["A/R aging in US dollars", "Credit holds and credit risk", "Dated exchange rates", "Tax: built-in rates, India GST, Avalara"],
     "howto": [{"q": "How do I add an exchange rate?", "steps": ["Admin → Tax & currency", "Enter currency, USD per unit and the effective date", "Add rate"]}]},
    {"key": "partners", "title": "Partners", "icon": "handshake", "pages": ["/partners", "/portal"], "roles": ["partner", "sales_manager"],
     "summary": "Partner programme: deal registration, co-selling, collateral and commissions.",
     "capabilities": ["Partner portal", "Deal registration approval", "Partner attribution on deals"],
     "howto": [{"q": "How do partners register a deal?", "steps": ["Partner signs in to the portal", "Registers the opportunity", "A channel manager approves it"]}]},
    {"key": "workflows", "title": "Workflows & automation", "icon": "workflow", "pages": ["/admin/workflows"], "roles": ["super_admin"],
     "summary": "No-code rules: when a record is created, changed or on a schedule, run steps with waits and branches.",
     "capabilities": ["Tasks, notifications, field updates, events, webhooks, Slack / Teams", "Waits and if / otherwise branches",
                      "Dry runs", "Run log with resume and cancel"],
     "howto": [{"q": "How do I automate a follow-up?", "steps": ["Admin → Workflows → New workflow", "Choose record type and trigger",
                                                                 "Add conditions", "Add steps (e.g. wait 2 days, then create a task)", "Test, then switch it on"]}]},
    {"key": "ai-governance", "title": "AI governance", "icon": "shield", "pages": ["/admin?tab=ai"], "roles": ["super_admin", "auditor"],
     "summary": "AI budgets, personal-data masking, prompt-injection screening, the AI log and what AI agents may change.",
     "capabilities": ["Spend per person and feature", "Budgets and daily limits", "Masking and injection settings", "Agent permissions and approval mode"],
     "howto": [{"q": "How do I limit AI spend?", "steps": ["Admin → AI governance", "Set monthly budgets and daily call limits", "Save"]}]},
    {"key": "admin", "title": "Administration & security", "icon": "shield", "pages": ["/admin"], "roles": ["super_admin", "auditor"],
     "summary": "Users, roles and permissions, sign-in security, audit, privacy, duplicates and configuration.",
     "capabilities": ["Roles & permissions matrix with own / all scope", "Two-factor and SSO", "Append-only audit trail",
                      "Validation and sharing rules", "Configuration export / import"],
     "howto": [{"q": "How do I give someone more access?", "steps": ["Admin → Users to change their role", "or Admin → Roles & permissions to change what a role can do"]}]},
    {"key": "platform", "title": "Custom objects & fields", "icon": "boxes", "pages": ["/admin?tab=objects", "/objects"], "roles": ["super_admin"],
     "summary": "Extend Cirra with your own fields and record types, with reports, list views and rules.",
     "capabilities": ["Typed custom fields with field-level security", "Custom objects with pages, reports and API"],
     "howto": [{"q": "How do I add a field?", "steps": ["Admin → Custom fields", "Choose the record type and field type", "Save; it appears on forms, reports and filters"]}]},
    {"key": "data", "title": "Import, export & integrations", "icon": "database", "pages": ["/admin?tab=data", "/admin?tab=developer"], "roles": ["super_admin"],
     "summary": "Bring data in with auto-mapping and validation, export it, and connect other systems via API keys and webhooks.",
     "capabilities": ["CSV / JSON import with dry run and rollback", "Scoped export", "API keys and signed webhooks", "Upsert API by external id"],
     "howto": [{"q": "How do I import accounts?", "steps": ["Admin → Import / export", "Upload the file", "Check the suggested column mapping", "Run the dry run, then import"]}]},
    {"key": "privacy", "title": "Privacy & consent", "icon": "lock", "pages": ["/admin?tab=privacy"], "roles": ["super_admin", "auditor", "marketing"],
     "summary": "Consent records, opt-outs and right-to-erasure with cryptographic shredding and evidence.",
     "capabilities": ["Consent ledger", "Opt-outs enforced on every send", "Erasure with evidence log"],
     "howto": [{"q": "How do I erase a person's data?", "steps": ["Open the contact", "Choose Erase personal data and confirm", "The erasure is logged as evidence"]}]},
]

PROCESSES = [
    {"key": "lead-to-cash", "title": "Lead to cash", "summary": "From first interest to an order in the ERP.",
     "lanes": ["Marketing", "SDR", "Account Executive", "Sales Manager", "System"],
     "steps": [
         {"id": "capture", "label": "Lead captured", "lane": "Marketing", "page": "/leads", "detail": "Web form, campaign, import or API; duplicates checked."},
         {"id": "score", "label": "Scored & routed", "lane": "System", "page": "/leads", "detail": "Fit + engagement score; assignment rules pick the owner."},
         {"id": "qualify", "label": "Qualified", "lane": "SDR", "page": "/leads", "detail": "BANT or MEDDPICC criteria confirmed."},
         {"id": "convert", "label": "Converted", "lane": "SDR", "page": "/leads", "detail": "Account, contact and opportunity created."},
         {"id": "discover", "label": "Discovery & demo", "lane": "Account Executive", "page": "/pipeline", "detail": "Stage gates ask for evidence at each step."},
         {"id": "quote", "label": "Quote", "lane": "Account Executive", "page": "/quotes", "detail": "Priced from price books; tax estimated."},
         {"id": "approve", "label": "Approve discount", "lane": "Sales Manager", "page": "/approvals", "detail": "Chain: manager → deal desk → VP → finance → legal."},
         {"id": "sign", "label": "Order form signed", "lane": "Account Executive", "page": "/quotes", "detail": "Customer signs by link; company countersigns in Cirra."},
         {"id": "won", "label": "Closed-Won", "lane": "Account Executive", "page": "/pipeline", "detail": "Order readiness checks must pass."},
         {"id": "order", "label": "Order to ERP", "lane": "System", "page": "/orders", "detail": "Order created from the primary quote and sent to the ERP."},
     ]},
    {"key": "case", "title": "Customer case", "summary": "From a customer email to a solved case and a satisfaction score.",
     "lanes": ["Customer", "System", "Support Agent"],
     "steps": [
         {"id": "email", "label": "Customer emails support", "lane": "Customer", "page": "/cases/inbox", "detail": "Or a portal / phone case is logged."},
         {"id": "case", "label": "Case created", "lane": "System", "page": "/cases", "detail": "Matched to contact and account; SLA timers start."},
         {"id": "route", "label": "Routed to an agent", "lane": "System", "page": "/cases/routing", "detail": "Least-loaded or presence-based."},
         {"id": "work", "label": "Investigate & reply", "lane": "Support Agent", "page": "/cases", "detail": "Replies email the customer; suggested articles help."},
         {"id": "resolve", "label": "Resolved", "lane": "Support Agent", "page": "/cases", "detail": "Resolution recorded."},
         {"id": "csat", "label": "CSAT survey", "lane": "Customer", "page": "/cases", "detail": "Customer rates the service."},
     ]},
    {"key": "campaign", "title": "Campaign to pipeline", "summary": "How marketing activity turns into attributed pipeline.",
     "lanes": ["Marketing", "System", "SDR"],
     "steps": [
         {"id": "plan", "label": "Plan campaign", "lane": "Marketing", "page": "/campaigns", "detail": "Budget, dates and a tracking code."},
         {"id": "members", "label": "Build the list", "lane": "Marketing", "page": "/campaigns", "detail": "Members from report filters; consent checked."},
         {"id": "send", "label": "Email & journeys", "lane": "System", "page": "/campaigns", "detail": "Sent in the background; opens and clicks tracked."},
         {"id": "engage", "label": "Engagement scored", "lane": "System", "page": "/leads", "detail": "Engagement raises lead scores."},
         {"id": "mql", "label": "MQL hand-off", "lane": "SDR", "page": "/leads", "detail": "Leads over the threshold are worked by SDRs."},
         {"id": "attribute", "label": "Attribution & ROI", "lane": "Marketing", "page": "/campaigns", "detail": "Sourced and influenced pipeline per campaign."},
     ]},
    {"key": "deal-desk", "title": "Discount approval", "summary": "How a quote needing approval moves through the chain.",
     "lanes": ["Account Executive", "Sales Manager", "Deal Desk / Finance / Legal"],
     "steps": [
         {"id": "build", "label": "Build quote", "lane": "Account Executive", "page": "/quotes", "detail": "Discount, terms, deal size."},
         {"id": "submit", "label": "Submit", "lane": "Account Executive", "page": "/quotes", "detail": "Policies decide the levels needed."},
         {"id": "mgr", "label": "Manager approves", "lane": "Sales Manager", "page": "/approvals", "detail": "Level 1."},
         {"id": "desk", "label": "Further levels", "lane": "Deal Desk / Finance / Legal", "page": "/approvals", "detail": "Each decides after the previous level."},
         {"id": "approved", "label": "Approved quote", "lane": "Account Executive", "page": "/quotes", "detail": "Ready for the order form."},
     ]},
    {"key": "renewal", "title": "Renewal", "summary": "Keeping customers: onboarding to renewal.",
     "lanes": ["Customer Success", "System", "Account Executive"],
     "steps": [
         {"id": "onboard", "label": "Onboarding", "lane": "Customer Success", "page": "/success", "detail": "Milestones from the won deal."},
         {"id": "adopt", "label": "Adoption & health", "lane": "System", "page": "/success", "detail": "Usage and health scoring."},
         {"id": "renew", "label": "Renewal deal opened", "lane": "System", "page": "/pipeline", "detail": "Ahead of the contract end date."},
         {"id": "close", "label": "Renewal won", "lane": "Account Executive", "page": "/pipeline", "detail": "New contract created."},
     ]},
    {"key": "ai-suggestion", "title": "AI suggestion", "summary": "How an AI agent's change is proposed, approved and recorded.",
     "lanes": ["AI agent", "Deal owner", "System"],
     "steps": [
         {"id": "detect", "label": "Agent spots something", "lane": "AI agent", "page": "/approvals?tab=ai", "detail": "e.g. a close date has passed."},
         {"id": "propose", "label": "Suggestion with reasons", "lane": "AI agent", "page": "/approvals?tab=ai", "detail": "Within the agent's permissions only."},
         {"id": "decide", "label": "Approve or reject", "lane": "Deal owner", "page": "/approvals?tab=ai", "detail": "Or applied automatically if the policy says so."},
         {"id": "apply", "label": "Change applied & recorded", "lane": "System", "page": "/approvals?tab=ai", "detail": "Kept for review in All activity."},
     ]},
]

GLOSSARY = {
    "Account": "A company you sell to or serve.", "Contact": "A person at an account.", "Lead": "An unqualified person or company showing interest.",
    "Opportunity / Deal": "A potential sale with an amount, stage and close date.", "Stage gate": "Evidence a deal needs before entering a stage.",
    "MQL": "Marketing-qualified lead: over the scoring threshold.", "BANT": "Budget, Authority, Need, Timeline qualification.",
    "MEDDPICC": "Metrics, Economic buyer, Decision criteria, Decision process, Paper process, Identify pain, Champion, Competition.",
    "Weighted pipeline": "Deal amounts × probability, discounted for risk.", "Forecast category": "Commit, best case, pipeline or omitted.",
    "Price book": "A set of prices: list, customer-specific or regional.", "Bundle": "A product that includes other products.",
    "ACV / TCV": "Annual and total contract value.", "Revenue split": "Share of a deal credited to a person; revenue splits total 100%.",
    "Overlay split": "Extra credit for specialists, on top of revenue credit.", "Deal team": "People working a deal with read or edit access.",
    "SLA": "Service-level target: first response and resolution times per case priority.", "CSAT": "Customer satisfaction score after a case.",
    "Journey": "A multi-step nurture of emails and waits with branches.", "Attribution": "Which campaigns sourced or influenced pipeline.",
    "Quick-Log": "Aiden's notes-to-CRM capture (⌘K).", "Agent": "An AI that proposes changes under an admin policy.",
    "Own / all scope": "Whether a role sees only its own records or everyone's.", "Custom object": "A record type your admin added.",
    "Workflow": "A no-code automation rule.", "Territory": "A set of accounts assigned by criteria.",
}

SHORTCUTS = [("⌘K / Ctrl+K", "Quick-Log and search"), ("⌘J / Ctrl+J", "Open Aiden"), ("?", "Help for this page"),
             ("Enter", "Send a question to Aiden"), ("Shift+Enter", "New line in Aiden")]

WHATS_NEW = [
    {"date": "2026-09-28", "title": "Help center & Aiden help answers", "items": ["Role guides, process maps, a live data model and page help", "Ask Aiden 'how do I…' questions"]},
    {"date": "2026-09-28", "title": "Reliability & security", "items": ["Workflow triggers survive restarts", "Campaign email sends in the background",
                                                                      "Sent mail always syncs", "Signing links expire; countersign in Cirra"]},
    {"date": "2026-09-28", "title": "AI governance & selling depth", "items": ["AI budgets, masking and approvals", "Deal products, teams and splits",
                                                                              "Workflow waits and branches", "Tax engines and dated exchange rates",
                                                                              "Two-way calendar sync", "Your language and time zone"]},
]

# The business entities shown in the data model explorer: table -> (label, description, area)
ENTITIES = {
    "accounts": ("Account", "A company you sell to or serve; parent of contacts, deals, cases and contracts.", "accounts"),
    "contacts": ("Contact", "A person at an account, with buying role and consent.", "accounts"),
    "leads": ("Lead", "Unqualified interest; converts into account, contact and deal.", "leads"),
    "deals": ("Opportunity", "A potential sale moving through pipeline stages.", "pipeline"),
    "deal_line_items": ("Opportunity product", "A product on a deal before quoting.", "pipeline"),
    "deal_team_members": ("Deal team member", "A colleague working the deal.", "pipeline"),
    "deal_splits": ("Deal split", "Revenue or overlay credit for a person.", "pipeline"),
    "activities": ("Activity", "A call, meeting, email or note on the timeline.", "activities"),
    "tasks": ("Task", "A to-do with due date and assignee.", "activities"),
    "products": ("Product", "Something you sell.", "cpq"),
    "price_books": ("Price book", "Customer or regional prices.", "cpq"),
    "quotes": ("Quote", "Priced offer for a deal.", "cpq"),
    "quote_lines": ("Quote line", "A product on a quote.", "cpq"),
    "documents": ("Document", "Generated agreement with versions and signatures.", "documents"),
    "orders": ("Order", "Sent to the ERP after Closed-Won.", "orders"),
    "contracts": ("Contract", "Active agreement with start / end dates.", "success"),
    "invoices": ("Invoice", "From the ERP, for receivables.", "finance"),
    "support_tickets": ("Case", "A customer support case with SLA.", "service"),
    "kb_articles": ("Knowledge article", "Help content for customers and agents.", "service"),
    "campaigns": ("Campaign", "A marketing programme with members and email.", "campaigns"),
    "campaign_members": ("Campaign member", "A lead or contact in a campaign.", "campaigns"),
    "journeys": ("Journey", "A multi-step nurture.", "campaigns"),
    "partners": ("Partner", "A reseller or referral partner.", "partners"),
    "onboarding_projects": ("Onboarding project", "Post-sale onboarding milestones.", "success"),
    "users": ("User", "A person using Cirra, with a role.", "admin"),
}
