"""Move Cirra's data between databases (see docs/database-portability.md).

    python -m app.dbtools schema --target URL                 create every table, constraint and index on the target
    python -m app.dbtools copy   --target URL [--source URL]  copy all rows, parents before children, in batches
    python -m app.dbtools verify --target URL [--source URL]  compare row counts table by table

URLs are synchronous SQLAlchemy URLs (``mysql+pymysql://``, ``mssql+pyodbc://``, ``oracle+oracledb://``,
``sqlite:///``, ``postgresql+psycopg2://``); the source defaults to this install's DATABASE_URL. Install the target's
driver first. A PostgreSQL target should be built with ``alembic upgrade head`` instead of ``schema``: the migrations
also create the append-only ledger triggers and extensions that ``Base.metadata`` doesn't describe.
"""
from __future__ import annotations

import argparse
import sys

from sqlalchemy import BigInteger, Integer, create_engine, func, select, text
from sqlalchemy.engine import Connection, Engine

import app.models  # noqa: F401 - registers every table and the schema rules
from app.core.config import settings
from app.core.database import Base
from app.core.types import POSTGRES_ONLY


def sync_url(url: str) -> str:
    return url.replace("+asyncpg", "+psycopg2").replace("+aiosqlite", "").replace("+aiomysql", "+pymysql")


def copyable_columns(table) -> list:
    """Columns whose values travel: not database-generated (tsvector), not Postgres-only."""
    return [c for c in table.columns if c.computed is None and not c.info.get(POSTGRES_ONLY)]


def create_schema(target: Engine) -> None:
    Base.metadata.create_all(target)


def _identity_column(table):
    pk = list(table.primary_key.columns)
    if len(pk) == 1 and isinstance(pk[0].type, (Integer, BigInteger)) and pk[0].autoincrement in (True, "auto"):
        return pk[0]
    return None


def _without_fk_checks(conn: Connection, on: bool) -> None:
    name = conn.dialect.name
    if name == "postgresql":
        conn.execute(text(f"SET session_replication_role = {'replica' if on else 'origin'}"))
    elif name in ("mysql", "mariadb"):
        conn.execute(text(f"SET FOREIGN_KEY_CHECKS = {0 if on else 1}"))
    elif name == "sqlite":
        conn.execute(text(f"PRAGMA foreign_keys = {'OFF' if on else 'ON'}"))
    elif name == "mssql":
        for table in Base.metadata.sorted_tables:
            conn.execute(text(f"ALTER TABLE [{table.name}] {'NOCHECK' if on else 'WITH CHECK CHECK'} CONSTRAINT ALL"))
    # Oracle and others: rows go in parents-first order (metadata.sorted_tables); self-references are ordered below


def _parents_first(table, rows: list[dict]) -> list[dict]:
    """Order rows so a self-referencing parent (users.manager_id, accounts.parent_id) precedes its children."""
    selfs = [fk.parent.name for fk in table.foreign_keys if fk.column.table is table]
    if not selfs or len(table.primary_key.columns) != 1:
        return rows
    pk = list(table.primary_key.columns)[0].name
    placed, out, pending = set(), [], rows
    while pending:
        nxt = [r for r in pending if all(r.get(c) is None or r[c] in placed or r[c] == r[pk] for c in selfs)]
        if not nxt:  # a cycle: keep the rest as they are
            nxt = pending
        out += nxt
        placed.update(r[pk] for r in nxt)
        ids = {id(r) for r in nxt}
        pending = [r for r in pending if id(r) not in ids]
    return out


def _reset_identity(conn: Connection, table) -> None:
    col = _identity_column(table)
    if col is None:
        return
    top = conn.execute(select(func.max(col))).scalar()
    if top is None:
        return
    name = conn.dialect.name
    if name == "postgresql":
        conn.execute(text(f"SELECT setval(pg_get_serial_sequence('{table.name}', '{col.name}'), :v)"), {"v": top})
    elif name == "oracle":
        conn.execute(text(f'ALTER TABLE "{table.name.upper()}" MODIFY "{col.name.upper()}" GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)'))
    # MySQL, SQLite: AUTO_INCREMENT continues after the highest value; SQL Server: IDENTITY_INSERT keeps the seed current


def copy_data(source: Engine, target: Engine, batch: int = 1000, out=sys.stdout) -> dict[str, int]:
    counts: dict[str, int] = {}
    with source.connect() as src, target.begin() as dst:
        _without_fk_checks(dst, True)
        for table in Base.metadata.sorted_tables:
            cols = copyable_columns(table)
            rows = [dict(r) for r in src.execute(select(*cols)).mappings()]
            rows = _parents_first(table, rows)
            identity = dst.dialect.name == "mssql" and _identity_column(table) is not None
            if identity:
                dst.execute(text(f"SET IDENTITY_INSERT [{table.name}] ON"))
            for i in range(0, len(rows), batch):
                dst.execute(table.insert(), rows[i:i + batch])
            if identity:
                dst.execute(text(f"SET IDENTITY_INSERT [{table.name}] OFF"))
            _reset_identity(dst, table)
            counts[table.name] = len(rows)
            print(f"  {table.name}: {len(rows)}", file=out)
        _without_fk_checks(dst, False)
    return counts


def row_counts(engine: Engine) -> dict[str, int]:
    with engine.connect() as conn:
        return {t.name: conn.execute(select(func.count()).select_from(t)).scalar_one() for t in Base.metadata.sorted_tables}


def verify(source: Engine, target: Engine) -> list[str]:
    a, b = row_counts(source), row_counts(target)
    return [f"{t}: source {a[t]}, target {b.get(t)}" for t in a if a[t] != b.get(t)]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m app.dbtools", description=__doc__.split("\n\n")[0])
    parser.add_argument("command", choices=["schema", "copy", "verify"])
    parser.add_argument("--target", required=True)
    parser.add_argument("--source", default=None)
    parser.add_argument("--batch", type=int, default=1000)
    args = parser.parse_args(argv)
    target = create_engine(sync_url(args.target))
    source = create_engine(sync_url(args.source or settings.database_url))
    if args.command == "schema":
        if target.dialect.name == "postgresql":
            print("PostgreSQL target: run `alembic upgrade head` against it instead (triggers, extensions).")
            return 2
        create_schema(target)
        print(f"Created {len(Base.metadata.tables)} tables on {target.dialect.name}.")
    elif args.command == "copy":
        total = sum(copy_data(source, target, args.batch).values())
        print(f"Copied {total} rows.")
    else:
        problems = verify(source, target)
        print("\n".join(problems) if problems else "Row counts match on every table.")
        return 1 if problems else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
